-- Trading Journal email automation additions.
-- Run this once in Supabase SQL Editor after supabase-rls.sql.

alter table public.trades add column if not exists source text;
alter table public.trades add column if not exists source_id text;
alter table public.trades add column if not exists exit_date date;
alter table public.notes add column if not exists source text;
alter table public.notes add column if not exists source_id text;
alter table public.summaries add column if not exists source text;
alter table public.summaries add column if not exists source_id text;

drop index if exists public.trades_user_source_id_unique;
create unique index if not exists trades_user_source_id_unique
on public.trades(user_id, source_id);

drop index if exists public.notes_user_source_id_unique;
create unique index if not exists notes_user_source_id_unique
on public.notes(user_id, source_id);

create table if not exists public.automation_import_events (
  id bigint generated by default as identity primary key,
  source_id text not null unique,
  source text not null,
  status text not null,
  email_from text,
  email_subject text,
  email_date timestamptz,
  details jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.automation_import_events enable row level security;
